services:
  db:
    image: mysql
    restart: always
    container_name: todo-db
    environment:
      MYSQL_DATABASE: todos
      MYSQL_USER: todouser
      MYSQL_PASSWORD: todopass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  todo-back:
    build:
      context: ./todo-back
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      DB_HOST: "todo-db"
      DB_PORT: 3306
      DB_USERNAME: todouser
      DB_PASSWORD: todopass
      DB_DATABASE: todos
      NODE_ENV: production

  todo-front:
    build:
      context: ./todo-front
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

volumes:
  mysql_data: